apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docdb-admin-external-secret
  namespace: cinevision-prod-dr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cinevision-secret-store
    kind: ClusterSecretStore
  target:
    name: docdb-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: DOCDB_ADMIN_USER
      remoteRef:
        key: /cinevision/prod-dr/database-credentials
        property: docdb_master_username
    - secretKey: DOCDB_ADMIN_PASSWORD
      remoteRef:
        key: /cinevision/prod-dr/database-credentials
        property: docdb_master_password
