apiVersion: v1
kind: ConfigMap
metadata:
  name: cinevision-config
data:
  POSTGRES_HOST: "cinevision-dev-postgres.cqty8224w3j4.us-east-1.rds.amazonaws.com"
  MONGO_HOST: "cinevision-dev-docdb.cluster-cqty8224w3j4.us-east-1.docdb.amazonaws.com"
  MONGO_DATABASE: "cinevision"
  MONGO_AUTH_SOURCE: "user"
  REDIS_HOST: "master.cinevision-dev-redis.lzqxbh.use1.cache.amazonaws.com"
  SPRING_DATA_REDIS_SSL_ENABLED: "true"
  KAFKA_BOOTSTRAP_SERVERS: "b-1.cinevisiondevmsk.17el86.c1.kafka.us-east-1.amazonaws.com:9094,b-2.cinevisiondevmsk.17el86.c1.kafka.us-east-1.amazonaws.com:9094,b-3.cinevisiondevmsk.17el86.c1.kafka.us-east-1.amazonaws.com:9094"
  KAFKA_SECURITY_PROTOCOL: "SSL"
  SPRING_KAFKA_SECURITY_PROTOCOL: "SSL"
  MAIL_HOST: "mailhog.cinevision-dev.svc.cluster.local"
